server:
  port: 8002

spring:
  application:
    name: provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: ckj
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ckj.entities

management:
  endpoints:
    web:
      exposure:
        include: "*"
