server:
  port: 80
spring:
  application:
    name: grid-server-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址

service-url:
  nacos-user-service: http://127.0.0.1:8001