server:
  port: 85
spring:
  application:
    name: feign-nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8917

service-url:
  nacos-user-service: http://provider-payment

feign:
  client:
    config:
      default:
        ConnectTimeOut: 5000
        ReadTimeout: 5000

logging:
  level:
    com.ckj.service.PaymentFeignService: debug
